language: go

go:
  - 1.6
  - tip

env:
  global:
    - BUILD_GOARCH=amd64
  matrix:
    - BUILD_GOOS=linux

script:
  - go fmt ./...
  - go test -v -race ./util/

after_success:
  - if [ "$TRAVIS_GO_VERSION" = "1.5" ] && [ "$BUILD_GOOS" = "linux" ] && [ "$TRAVIS_TAG" != "" ]; then ./scripts/cross_compile.sh; ghr --username wallyqs --token $GITHUB_TOKEN --replace --debug $TRAVIS_TAG pkg/ ; fi
