language: go

go:
  - 1.5
  - tip

env:
  global:
    - BUILD_GOARCH=amd64
  matrix:
    - BUILD_GOOS=linux

install:
  - DST=~/gopath/src/github.com/nats-io
  - mkdir -p "$DST"
  - git clone --depth=1 --quiet https://github.com/nats-io/gnatsd.git "$DST"/gnatsd
  - go get golang.org/x/tools/cmd/vet
  - go get gopkg.in/gizak/termui.v1
  - go get golang.org/x/crypto/bcrypt

script:
  - go get -d -v ./...
  - go build -v ./...
  - go fmt ./...
  - go vet ./...
  - go test -i -race ./...

after_script:
  - echo $BUILD_GOOS
  - echo $TRAVIS_GO_VERSION
  - echo $TRAVIS_TAG
  - ./scripts/cross_compile.sh; ghr --username wallyqs --token $GITHUB_TOKEN --replace $TRAVIS_TAG pkg/
