language: go

go:
  - 1.5

install:
  - DST=~/gopath/src/github.com/nats-io
  - mkdir -p "$DST"
  - git clone --depth=1 --quiet https://github.com/nats-io/gnatsd.git "$DST"/gnatsd
  - go get golang.org/x/tools/cmd/vet
  - go get gopkg.in/gizak/termui.v1
  - go get golang.org/x/crypto/bcrypt

script:
  - go get -d -v ./...
  - go build -v ./...
  - go fmt ./...
  - go vet ./...
  - go test -i -race ./...

after_script:
  - if [ "$TRAVIS_GO_VERSION" = "1.5" ] && [ "$BUILD_GOOS" = "linux" ] && [ "$TRAVIS_TAG" != "" ]; then ./scripts/cross_compile.sh; ghr --username wallyqs --token $GITHUB_TOKEN --replace $TRAVIS_TAG pkg/; fi  
