language: go

go:
  - 1.5
  - tip

env:
  global:
    - BUILD_GOARCH=amd64
  matrix:
    - BUILD_GOOS=linux

install:
  - go get github.com/nats-io/gnatsd
  - go get golang.org/x/tools/cmd/vet
  - go get gopkg.in/gizak/termui.v1
  - go get golang.org/x/crypto/bcrypt

script:
  - go get -d -v ./...
  - go build -v ./...
  - go fmt ./...
  - go vet ./...
  - go test -i -race ./...

after_success:
  - echo $BUILD_GOOS
  - echo $TRAVIS_GO_VERSION
  - echo $TRAVIS_TAG
  - if [ "$TRAVIS_GO_VERSION" = "1.5" ] && [ "$BUILD_GOOS" = "linux" ] && [ "$TRAVIS_TAG" != "" ]; then ./scripts/cross_compile.sh; ghr --username wallyqs --token $GITHUB_TOKEN --replace --prerelease --debug $TRAVIS_TAG pkg/ ; fi
